name: evaluate predictions

on:   
# run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  evaluate-predictions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: update submodule
        run: |
          git pull origin main
          git submodule init
          git submodule update
          git submodule update --remote
          git submodule foreach git pull origin main
          
# access repo and set up python
      - name: python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
         
      - name: install dependencies
        run: |
          pip install -r pip_requirements.txt
          cd ./scorepi
          pip install -e .

# transform data and push to repo
      - name: run evaluations
        run: |
          git pull
          python epistorm_evaluations.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add evaluations/*
          git commit -m "generate evaluations via github actions"
          git push
