name: plot_evaluations

on:
  workflow_dispatch:
  
jobs:
  plot-evaluations:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
          ref: main  # Explicitly checkout main
          
      - name: python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
         
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pip_requirements.txt

      - name: run evaluations
        run: |
          python plots.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add plots/*
          git commit -m 'generate plots via github actions'
          git push
